# Generated by Django 2.2.8 on 2019-12-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191219_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name',), 'verbose_name': 'contato', 'verbose_name_plural': 'contatos'},
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
